server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        histogram-flavor: prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: '*'
        readiness:
          include: '*'
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    elasticsearch:
      enabled: false
spring:
  kafka:
    ssl-key-password: password
    ssl-cert-location: cert.crt
    enable-ssl: false
    consumer:
      retries: 3
      bootstrap-servers: localhost:9092
      group-id: spring-boot-kafka-consumer-sample
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic: sample-topic
